<a href="https://colab.research.google.com/github/sharvithaa/MLpraticeBYTS/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l1=[1,2,3,4,5,6]
l1.append(10)
print(l1)

[1, 2, 3, 4, 5, 6, 10]


In [ ]:
l1.extend([11,12])
print(l1)

[1, 2, 3, 4, 5, 6, 10, 11, 12]


In [ ]:
l1.pop(2)

3

In [ ]:
l1.remove(2)
l1

[1, 4, 5, 6, 10, 11, 12]

In [ ]:
#del l1
#l1


In [ ]:
l1=[1,2,3,4,5,6]
l1.insert(2,5)
l1

[1, 2, 5, 3, 4, 5, 6]

In [ ]:
import numpy as np
l=[[1,2],[3,4],[5]]
arr1=np.array(l)
arr1.shape
l1=[[1,2],[3,4]]
arr2=np.array(l1)
arr2.shape

<ipython-input-16-aaf0f878c200>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1=np.array(l)


(2, 2)

In [ ]:
l3=np.arange(5,12,2)

l3

array([ 5,  7,  9, 11])

In [ ]:
a=np.array([1,2,3,4],dtype=np.float64)  #to forcefully change datatype
a

array([1., 2., 3., 4.])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(np.ones(5))
print(np.ones((3,2)))
print(np.ones((2,3,4)))
print(np.ones((2,3,4,5,6)))

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[[[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]]


  [[[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]

   [[1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]
    [1. 1. 1. 1. 1. 1.]]


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
print(np.random.random(5)) #from 0 to 1
np.random.randint(2,100)

[0.00527611 0.32459664 0.55310768 0.26367122 0.89946468]


67

In [ ]:
np.full((2,2),10)


array([[10, 10],
       [10, 10]])

In [ ]:
np.eye(2) #identity matrix

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.linspace(0.,1.,num=5)  #like arange() with no of elements needed and decimal eg 0 to 1 la 5 times split agum

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a2=np.array([[1,2],[3,4],[5,6]])
print(a2[0][1])
print(a2[1:3,0]) #slicing lowerlimit included upperlimit excluded
print(a2[1:3,1])


2
[3 5]
[4 6]


In [ ]:
a3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a3.shape
print(a3[:2,1:3])


[[2 3]
 [6 7]]


In [ ]:
print(a3[1,:],a3[1,:].shape)
print(a3[1:2 ,:],a3[1:2 ,:].shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [ ]:
print(a3[:,1])
print(a3[:,1:2])

[ 2  6 10]
[[ 2]
 [ 6]
 [10]]


In [ ]:
a4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b=np.array([0,1,2,3])
print(a4[np.arange(4),b])
#b1=(a4[np.arange(4),b] )+=10
#print(b1)

[ 1  6 11 16]


In [ ]:
bool_idx=(a4>2)
bool_idx

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
print(np.argmax(a4))
print(np.argmin(a4))
print(np.argsort(a4))
print(np.argsort(a4)[::-1])
print(np.where(a4>5)[0])
print(np.where(a4>=a4[np.argmin(a4)])[0])


15
0
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[1 1 1 2 2 2 2 3 3 3 3]
[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3]


In [ ]:
a5=[[1,5,3],[6,5,2]]
print(np.sort(a5,axis=1,kind='heapsort'))  #0-rows 1-columns


[[1 3 5]
 [2 5 6]]


In [ ]:
%%time
x=np.sum(a5)

addtion,sub,multiplication array should of same size-element wise operations
 dot product print(v.dot(w)),print(np.dot(v,w)),print(v @w)
 if one list is present then distirbutionis around col
 .min(),.max() -axis can also be done.
 transpose
 reshaping converting rows into col and vice versa
 .squeeze()/.reshape(-1)=reomve nested element


**BROADCASTING **
np.array([1,2,3])+1
extends and add

** RULES**
 Rule 1:fewer dim extends
 Rule 2:1 having dim extends
 Rule 3:if two dim